apiVersion: v1
kind: Pod
metadata:
  name: lsa-pod
  namespace: lsa
  labels:
    name: lsa-pod
    type: backend
spec:
  containers:
  - name: busybox--pod
    image: busybox
    resources:
      limits:
        memory: "16Mi"
        cpu: "100m"
    command: ['sh','-c','x=1; while true; do echo "Blitz Kubernetes!!! $x times" >> /pod-data/index.html; ((x ++)); sleep 1;  done']

