apiVersion: v1
kind: Pod
metadata:
  name: mc-pod
  namespace: mc
  labels:
    name: mc-pod
spec:
  volumes:
  - name:  mc-shared-data
    emptyDir: {}
  containers:
  - name: mc-nginx-con
    image: nginx
    volumeMounts:
      - mountPath: /user/share/nginx/html
        name: mc-shared-data
    resources:
      limits:
        memory: "32Mi"
        cpu: "250m"
    ports:
      - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
  - name: mc-busybox-con
    image: busybox
    volumeMounts:
      - mountPath: /pod-data
        name: mc-shared-data
    resources:
      limits:
        memory: "32Mi"
        cpu: "250m"
    command: ['sh','-c','x=1; while true; do echo "Blitz Kubernetes!!! $x times" >> /pod-data/index.html; ((x ++)); sleep 1;  done']
    livenessProbe:
      exec:
        command:
        - echo
        - testing
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe:
      exec:
        command:
        - echo
        - testing
      initialDelaySeconds: 5
      periodSeconds: 5