apiVersion: v1
kind: Pod
metadata:
  name: bb-pod-wsecret
  namespace: bb
  labels:
    name: bb-pod-wsecret
spec:
  containers:
  - name: bb-pod-wsecret
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ['sh','-c','echo "from busybox-pod-withsecret: secret is $(bb_mysecret_password) !!!" && sleep 300']
    env:
      - name: bb_mysecret_password
        valueFrom:
          secretKeyRef:
            name: bb-secret
            key: password
  restartPolicy: Never
